version: "3.8"

services:
  macrocore-db:
    image: postgres:15
    container_name: macrocore-game-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: macrocore_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - game_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d macrocore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  game_postgres_data: