server:
  port: 8080

spring:
  web:
    cors:
      allowed-origins: "http://localhost:5173,http://127.0.0.1:5173"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/macrocore_db
    username: user
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: game
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public

logging:
  level:
    org.grimjo.macrocore: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE